"""add_request_metrics_table

Revision ID: 4c0856d1f25a
Revises: '859769aa469e'
Create Date: 2026-08-04 11:43:32.624880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0856d1f25a'
down_revision: Union[str, None] = '859769aa469e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_metrics_created_at'), 'request_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_metrics_endpoint'), 'request_metrics', ['endpoint'], unique=False)
    op.create_index(op.f('ix_request_metrics_id'), 'request_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_request_metrics_status_code'), 'request_metrics', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_metrics_status_code'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_id'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_endpoint'), table_name='request_metrics')
    op.drop_index(op.f('ix_request_metrics_created_at'), table_name='request_metrics')
    op.drop_table('request_metrics')
    # ### end Alembic commands ###
