"""add_composite_index

Revision ID: 859769aa469e
Revises: '0003_enforce_alembic_only'
Create Date: 2026-08-04 11:26:36.584634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859769aa469e'
down_revision: Union[str, None] = '0003_enforce_alembic_only'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_genes_symbol_organism', 'genes', ['symbol', 'organism'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genes_symbol_organism', table_name='genes')
    # ### end Alembic commands ###
